# Operations for machine learning
#### John Cronin-McCartney
## NumPy
Working with Arrays, Matrices

### Vectors

In [ ]:
a_list = [1,2,3]

import numpy as np

a_arr = np.array(a_list)

print("This is a basic list in:",type(a_arr)," format. \nThis is the fundamental datatype used in numpy")
print("\nWe can print the array as a vector: ", a_arr)

This is a basic list in: <class 'numpy.ndarray'>  format. 
The fundamental datatype used in numpy

We can print the array as a vector:  [1 2 3]


### Matrices

In [ ]:
A_mat = [[1,2,3],[4,5,6],[7,8,9]]
np_mat = np.array(A_mat)

print("This is a matrix list in:",type(np_mat)," format. \nMatrices are easily handled with various numPy operations")
print("\nWe can print the matrix simply: \n", np_mat,"\n--------------")

print("NumPy arrays have a set of quickly accessible attributes for matrices:")
# nDim for dimension of np arrays, 1 for vectors, 2 for simple matrices, etc. 
print("Dimension of matrix: ", np_mat.ndim, sep='')

# Matrix size gives us the total number of elements in our array/matrix
print("Size of the matrix: ", np_mat.size,sep='')

# Matrix Shape returns the sixe of each axis in our np array.
print("Shape of the matrix: ", np_mat.shape,sep='')

# Data type contained in the array
print("Data type of this matrix: ",np_mat.dtype,sep='')

B_mat = [[1.1,2.2,3.3],[4,5,6],[7,8,9]]
np_mat = np.array(B_mat)

print("\n\nModified Matrix: \n", np_mat,"\n--------------")
print("Data type of this matrix: ",np_mat.dtype,sep='')

C_np_mat = np.array([(1.1,2,3),(4,5,6)])
print("\n\nWe can convert tuples to n-dimensional arrays also:")
print("By using C = np.array([(1.1,2,3),(4,5,6)])")
print("This a Matrix made from tuples, not lists\n",C_np_mat)

This is a matrix list in: <class 'numpy.ndarray'>  format. 
Matrices are easily handled with various numPy operations

We can print the matrix simply: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
--------------
NumPy arrays have a set of quickly accessible attributes for matrices:
Dimension of matrix: 2
Size of the matrix: 9
Shape of the matrix: (3, 3)
Data type of this matrix: int64


Modified Matrix: 
 [[1.1 2.2 3.3]
 [4.  5.  6. ]
 [7.  8.  9. ]] 
--------------
Data type of this matrix: float64


We can convert tuples to n-dimensional arrays also:
By using C = np.array([(1.1,2,3),(4,5,6)])
This a Matrix made from tuples, not lists
 [[1.1 2.  3. ]
 [4.  5.  6. ]]


## Programmatically generating arrays with ranges and spacing in NumPy
### np.arange

In [33]:
print("Creating an array with a series of numbers low to high:", np.arange(0,16))

Creating an array with a series of numbers low to high: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [31]:
print("Array with with integers spaced by 2:", np.arange(1,11,2))

Array with with integers spaced by 2: [1 3 5 7 9]


In [32]:
print("Array with spacing by float:",np.arange(50,-1,-5))

Array with spacing by float: [50 45 40 35 30 25 20 15 10  5  0]
